"""Production wrapper for Isaac Sim 6 RTX camera data.

It normalizes RTX's width-by-height array layout and USD-path semantic labels
before delegating to the shared camera observation provider.
"""

from __future__ import annotations

from typing import Any

from modules.perception import isaac_camera as base


class _HeightWidthSensor:
    def __init__(self, source: Any, width: int, height: int) -> None:
        self.source = source
        self.width = width
        self.height = height

    def get_data(self, name: str):
        import numpy as np

        result = self.source.get_data(name)
        if isinstance(result, tuple) and len(result) == 2:
            data, info = result
        else:
            data, info = result, {}
        if hasattr(data, "numpy"):
            data = data.numpy()
        array = np.asarray(data)
        if array.ndim >= 2 and array.shape[:2] == (self.width, self.height):
            data = np.swapaxes(array, 0, 1)
        return data, info


class IsaacCameraRealObservationProvider(base.IsaacCameraObservationProvider):
    """Camera provider used by the real Isaac Sim RGB-D integration."""

    def __init__(self, sensor: Any, camera_model: dict[str, Any], **kwargs: Any) -> None:
        width = int(camera_model.get("image_width", 640))
        height = int(camera_model.get("image_height", 480))
        normalized_model = dict(camera_model)
        normalized_model.pop("image_width", None)
        normalized_model.pop("image_height", None)
        super().__init__(_HeightWidthSensor(sensor, width, height), normalized_model, **kwargs)
        self._preferred_segmentation_annotator = self.segmentation_annotator

    def _candidate_ids(self, item: dict[str, Any], label_map: dict[str, set[int]]) -> set[int]:
        ids = super()._candidate_ids(item, label_map)
        for label in item.get("segmentation_labels", ()):
            short_label = str(label).rstrip("/").rsplit("/", 1)[-1]
            ids.update(label_map.get(short_label, set()))
            ids.update(label_map.get(f"/World/{short_label}", set()))
        return ids

    def observe(self) -> dict[str, Any]:
        """Prefer instance IDs, but fall back to semantic IDs when metadata is late.

        Isaac Sim can publish the RGB/depth buffers before the instance
        annotator's ``idToLabels`` map is populated.  The semantic annotator
        is generated by the same render product and usually has its class map
        ready earlier.  Retrying one frame through that annotator avoids
        treating a transient metadata gap as a scene with no objects.
        """

        self.segmentation_annotator = self._preferred_segmentation_annotator
        primary = super().observe()
        if len(primary.get("objects", [])) >= len(self.manifest):
            return primary

        fallback_annotator = "semantic_segmentation"
        if fallback_annotator == self.segmentation_annotator:
            return primary
        self.segmentation_annotator = fallback_annotator
        try:
            # Both reads belong to the same rendered frame.  The fallback is
            # allowed to reuse its timestamp; normal external callers still
            # get the strict monotonic timestamp gate from the base provider.
            fallback = super().observe(allow_timestamp_reuse=True)
        except (KeyError, RuntimeError, ValueError):
            return primary
        if len(fallback.get("objects", [])) > len(primary.get("objects", [])):
            fallback.setdefault("source", {})["segmentation_annotator"] = fallback_annotator
            fallback.setdefault("source", {})["segmentation_fallback"] = True
            self.last_metrics["segmentation_fallback"] = fallback_annotator
            return fallback
        self.segmentation_annotator = self._preferred_segmentation_annotator
        return primary
